### ISSUE TITLE
Please change names

### ISSUE THREAD

**Issue by dovy** [stoeffel/redux-io#3]
Please note redux.io is a registered DBA. Please use another name. Redux.js stole our name.

**Comment by eeue56** [comment]
This repo has existed since December 2015 ->https://github.com/stoeffel/redux-io/commit/5eafff9d0f22eda43e42b85e484a8e2fa4802289

It has also been published since 26th of December 2015 -> https://github.com/stoeffel/redux-io/commit/eb7341f24d4987a7c26f6a052eb50bfc537dd07b

The registered URL you talk about was reigstered `2016-07-04`

![screen shot 2016-10-19 at 21 44 47](https://cloud.githubusercontent.com/assets/1139198/19534730/4a78a95c-9645-11e6-9301-cc8148869fa7.png)

**Comment by eeue56** [comment]
(updated image so it no longer includes your address!)

**Comment by dovy** [comment]
Redux has been used by us since Nov 28, 2012: https://github.com/ghost1227/historical-redux2/commits/master?after=gWhHA%2BgnLUyUFTZnhbPZ3sGJudArMjA5

We operated as Redux at http://reduxframework.com

We grabbed the .io domain when they became reasonable in price.

I appreciate your changing of the image, but shortly I fear we may need to take other measures.

**Comment by eeue56** [comment]
This package is called redux-io, not reduxframework, nor Redux. It is named so because it works with the existing framework called Redux located here -> https://github.com/reactjs/redux

This package is not published at any url. It is clear from the README that is it not related to your framework -> https://github.com/stoeffel/redux-io

Your package is to do with Wordpress. It will be clear to anyone coming across this repo and package that it is entirely unrelated, as Wordpress is PHP based, not Node-based. if you were to publish a package to npm, I would assume you would call it redux or reduxframework, not redux-io. :)

**Comment by dovy** [comment]
You'd hope that, but we get endless redux.js users all the time. Just was hoping to avoid the confusion for everyone. Really just frustrated at redux.js. Alas. We'll be in touch eventually I wager. Thank you.

**Comment by eeue56** [comment]
Sadly there is no way to notify users of this package of any renames. As a result, it would be damaging to the users of this package to rename it. The best way to avoid confusion for users of this library is to keep the name the same. A search on npm for `redux` results in nearly 4000 results:

![screen shot 2016-10-19 at 22 10 59](https://cloud.githubusercontent.com/assets/1139198/19535666/fbedfebe-9648-11e6-92e5-e309804ecdc1.png)

I think the people who are confused and end up with your project are not the users of this package. They probably all come from Facebook's Redux. Or perhaps one of the other 4000 packages :)

**Comment by dovy** [comment]
Indeed. I just wish I had known about redux.js on release. Ahh well. 

Thanks again.
